version: '3'
services:
  react-app:
    container_name: kapp-docker-react
    restart: always
    build: './Client'
    ports:
      - '80:3000'
    networks:
     - kapp-app
  
  api-server:
    container_name: kapp-docker-express
    restart: always
    build: './Server'
    ports:
      - '5000:5000'
    networks:
     - kapp-app
    depends_on:
      - mongo    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - kapp-app
    volumes:
      - mongo-data:/data/db

networks:
  kapp-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
