version: '3'
services:
  react_client:
    container_name: kappindu-react
    restart: always
    image: 'soen390_19_react_client'
    ports:
      - '80:3000'
    networks:
     - kapp-app
  
  express_server:
    container_name: kappindu-express
    restart: always
    image: 'soen390_19_express_server'
    ports:
      - '5000:5000'
    networks:
     - kapp-app
    depends_on:
      - mongo    
  mongo:
    container_name: kappindu-mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - kapp-app
    volumes:
      - mongo-data:/data/db

networks:
  kapp-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
